[program:frps]
command=/app/frp/frps -c /app/configs/frps.yaml
autostart=true
autorestart=true
stdout_logfile=/app/logs/frps_stdout.log
stderr_logfile=/app/logs/frps_stderr.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile_backups=3
priority=20
user=frp
startsecs=3
startretries=3
stopwaitsecs=10
